apiVersion: apps/v1
kind: Deployment
metadata:
  name: derivco-create-container-config-error
  labels:
    app: derivco-create-error
spec:
  replicas: 2
  selector:
    matchLabels:
      app: derivco-create-error
  template:
    metadata:
      labels:
        app: derivco-create-error
    spec:
      containers:
      - name: crash-demo
        image: nginx:1.21.6
